# Generated by Django 2.1.5 on 2019-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SyainId', models.CharField(max_length=7)),
                ('PassWord', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('MorningOffFlg', models.BooleanField()),
                ('AfternoonOffFlg', models.BooleanField()),
            ],
        ),
    ]
